/**
 * What the home feed shows when Meta is unreachable: real posts, frozen.
 *
 * Generated by `npm run instagram:fallback`, which ranks the recent window by
 * views and keeps the best three. Do not edit by hand — re-run it after a
 * token rotation so the snapshot does not drift from the account.
 *
 * Captions stay in Spanish in all three languages, exactly like the live feed:
 * the posts themselves are Spanish, and only the chrome around them is
 * translated.
 *
 * Last generated: 2026-10-06
 */

import type { InstagramMediaType } from "./instagram-api";

export type FallbackPost = {
  permalink: string;
  caption: string;
  mediaType: InstagramMediaType;
  timestamp: string;
};

export const FALLBACK_POSTS: FallbackPost[] = [
  {
    permalink: "https://www.instagram.com/reel/Db_qlPHKj32/",
    caption: "Hoy me ha vuelto a pasar en Rocambolesc, en la Santa Market.\n\nSegún la web, la heladería aparece como sin gluten. Así que, como hago siempre, pregunto antes de pedir.\n\nY entonces llega la conversación:\n\n“Sí, es sin gluten… pero en el mismo obrador hacemos los panecillos. Tenemos un protocolo, abrimos vitrinas nuevas, limpiamos todo, nos lavamos las manos…”\n\nVale. Perfecto. ¿Entonces puedo comerlo con tranquilidad o no? 🤡\n\nPorque para una persona celíaca, “sin gluten” no debería significar “bueno, tenemos un protocolo y tú decides si te fías”.\n\nY aquí mi problema no es que un establecimiento no pueda ofrecer opciones aptas. Mi problema es que se anuncie como sin gluten cuando la información que recibes allí te hace salir con más dudas que cuando entraste.\n\nYo no necesito que me prometan que “tienen mucho cuidado”. Necesito saber qué puedo comer y que ese protocolo sea suficiente para garantizar que no haya contaminación cruzada.\n\nY por favor, reivindico una cosa: necesitamos más sitios que sean realmente sin gluten, que lo tengan claro y que puedan decirte un “sí, puedes comerlo” sin veinte asteriscos detrás.\n\nPorque salir a comer siendo celíaca ya requiere bastante trabajo como para tener que jugar también a ¿me intoxico o me tomo un helado?.\n\n@rrrocambolesc, @la_santamarket : si vais a poner “sin gluten”, haced que ese “sin gluten” signifique algo también para quienes vivimos sin gluten.\n\n#celiaquia #celiaca #singluten #glutenfree #contaminacioncruzada",
    mediaType: "video",
    timestamp: "2026-08-13T21:17:07+0000",
  },
  {
    permalink: "https://www.instagram.com/p/Dbbg8e-isH7/",
    caption: "Sí, estoy hasta el c*ño.\n\nDe los sitios que anuncian opciones “sin gluten” y, cuando por fin piensas que vas a poder pedir algo tranquila, aparece la letra pequeña que pone \"Puede contener trazas\".\n\nDe tener que investigar cada restaurante antes de salir de casa.\n\nDe no poder improvisar.\n\nDe explicar una y otra vez por qué no me puedo arriesgar.\n\n¿Y tú, de qué estás hasta el c💜ño?\n\n#celiaca #singluten #celíacos #vidaceliaca #glutenfree",
    mediaType: "carousel",
    timestamp: "2026-07-30T20:09:43+0000",
  },
  {
    permalink: "https://www.instagram.com/reel/Dduh190qvIt/",
    caption: "Cuando una celíaca encuentra un restaurante donde puede comer tranquila, repite. Y no va sola: se lleva a la pareja, a la familia, al cumpleaños de turno… Porque al final cuando elegimos nosotras dónde se come pensamos en ese sitio que va a gustarnos a nosotras y a los que nos acompañan.\n\nY tampoco pedimos tanto. Que al decir “soy celíaca” no te miren raro. Que el pan sin gluten venga aparte y no en la misma cesta. Que no tengas que explicar lo de la contaminación cruzada cada vez.\n\n¿Cuál es el vuestro? Decidme sitio y ciudad y hacemos lista entre todas 👇\n\n#singluten #celiaquia #restaurantessingluten #celiacos #singlutenbarcelona",
    mediaType: "video",
    timestamp: "2026-09-25T22:31:46+0000",
  },
];
