/**
 * Regenerates `lib/instagram-fallback.ts`: the most-viewed recent posts, frozen
 * so the home page has something real to show when Meta is unreachable.
 *
 *   npm run instagram:fallback
 *
 * Reads INSTAGRAM_ACCESS_TOKEN from the environment or from .env.local, like
 * the token script next door. Node runs this file's types away, which is why it
 * can import the same modules the site does instead of re-implementing them.
 *
 * Insights only reach back 90 days, so this ranks the recent window rather than
 * the account's whole history. Meta keeps nothing older.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { loadInstagramPosts } from "../lib/instagram-api.ts";
import {
  loadPostMetrics,
  selectTopPosts,
} from "../lib/instagram-stats-api.ts";
import type { FallbackPost } from "../lib/instagram-fallback.ts";
import { INSTAGRAM_API_BASE } from "../lib/site.ts";

/** Rank over a wide window, keep a few, show the near misses for context. */
const POOL = 50;
const KEEP = 3;
const SHOW = 8;

const TARGET = new URL("../lib/instagram-fallback.ts", import.meta.url);

function readToken(): string | undefined {
  if (process.env.INSTAGRAM_ACCESS_TOKEN) {
    return process.env.INSTAGRAM_ACCESS_TOKEN;
  }

  try {
    const env = readFileSync(new URL("../.env.local", import.meta.url), "utf8");
    const match = env.match(/^INSTAGRAM_ACCESS_TOKEN=(.*)$/m);
    return match?.[1].trim().replace(/^["']|["']$/g, "") || undefined;
  } catch {
    return undefined;
  }
}

function render(posts: FallbackPost[], generatedOn: string): string {
  const entries = posts
    .map(
      (post) => `  {
    permalink: ${JSON.stringify(post.permalink)},
    caption: ${JSON.stringify(post.caption)},
    mediaType: ${JSON.stringify(post.mediaType)},
    timestamp: ${JSON.stringify(post.timestamp)},
  },`,
    )
    .join("\n");

  return `/**
 * What the home feed shows when Meta is unreachable: real posts, frozen.
 *
 * Generated by \`npm run instagram:fallback\`, which ranks the recent window by
 * views and keeps the best three. Do not edit by hand — re-run it after a
 * token rotation so the snapshot does not drift from the account.
 *
 * Captions stay in Spanish in all three languages, exactly like the live feed:
 * the posts themselves are Spanish, and only the chrome around them is
 * translated.
 *
 * Last generated: ${generatedOn}
 */

import type { InstagramMediaType } from "./instagram-api";

export type FallbackPost = {
  permalink: string;
  caption: string;
  mediaType: InstagramMediaType;
  timestamp: string;
};

export const FALLBACK_POSTS: FallbackPost[] = [
${entries}
];
`;
}

async function main() {
  const token = readToken();
  if (!token) {
    throw new Error("INSTAGRAM_ACCESS_TOKEN is not set. See .env.example.");
  }

  const options = {
    token,
    apiBase: INSTAGRAM_API_BASE,
    limit: POOL,
    revalidateSeconds: 0,
  };

  const [posts, metrics] = await Promise.all([
    loadInstagramPosts(options),
    loadPostMetrics(options),
  ]);

  if (!posts) throw new Error("Instagram returned no usable posts");
  if (!metrics) throw new Error("Insights returned nothing for those posts");

  const ranked = selectTopPosts(posts, metrics, SHOW, "views");

  if (ranked.length === 0) {
    throw new Error("No post in the window has insights to rank by");
  }

  console.log(`Top ${ranked.length} of ${posts.length} fetched posts, by views:\n`);
  for (const [i, { post, metrics: m }] of ranked.entries()) {
    const kept = i < KEEP ? "keep" : "    ";
    const date = post.timestamp.slice(0, 10);
    const headline = (post.caption ?? "").split("\n")[0].slice(0, 54);
    console.log(
      `${kept}  ${String(m.views).padStart(8)} views  ${date}  ${headline}`,
    );
  }

  const chosen: FallbackPost[] = ranked.slice(0, KEEP).map(({ post }) => ({
    permalink: post.permalink,
    caption: post.caption ?? "",
    mediaType: post.mediaType,
    timestamp: post.timestamp,
  }));

  if (chosen.length < KEEP) {
    console.warn(`\nOnly ${chosen.length} posts had insights; wrote those.`);
  }

  writeFileSync(TARGET, render(chosen, new Date().toISOString().slice(0, 10)));
  console.log(`\nWrote ${chosen.length} posts to lib/instagram-fallback.ts.`);
}

try {
  await main();
} catch (error) {
  console.error(`Failed: ${(error as Error).message}`);
  process.exit(1);
}
